//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#include "CA_Library.h"
#include "/sources/esp-idf/components/esp_adc/include/esp_adc/adc_monitor.h"

// clang-format off

static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    CA_Library_ACDMonitor::SetupMonitor,
    CA_Library_ACDMonitor::DisposeMonitor,
    NULL,
    CA_Library_DirectGPIO::Read,
    CA_Library_DirectGPIO::Write,
    CA_Library_DirectGPIO::SetMode
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_CA_Library =
{
    "CA.Library",
    0x271EA60D,
    method_lookup,
    { 1, 0, 0, 0 }
};

// clang-format on
